### ISSUE TITLE
Fail to install strelka

### ISSUE THREAD

**Issue by Jemimacat** [genome-vendor/strelka#1]
Hi, I'm trying to install strelka on Centos 6 (without root), and it fails. Would someone please to help on this issue? Thank you.

After git clone strelka, I configure it:

> ./configure --host=arm-linux --prefix=$(pwd)/_install
> configure: WARNING: If you wanted to set the --build type, don't use --host.
>     If a cross compiler is detected then cross compile mode will be used.
> checking for arm-linux-gcc... no
> checking for gcc... gcc
> checking for C compiler default output file name... a.out
> checking whether the C compiler works... yes
> checking whether we are cross compiling... no
> checking for suffix of executables...
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking for arm-linux-g++... no
> checking for arm-linux-c++... no
> checking for arm-linux-gpp... no
> checking for arm-linux-aCC... no
> checking for arm-linux-CC... no
> checking for arm-linux-cxx... no
> checking for arm-linux-cc++... no
> checking for arm-linux-cl.exe... no
> checking for arm-linux-FCC... no
> checking for arm-linux-KCC... no
> checking for arm-linux-RCC... no
> checking for arm-linux-xlC_r... no
> checking for arm-linux-xlC... no
> checking for g++... g++
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> configure: creating ./config.status
> config.status: creating Makefile

Then I make

> make -C /ifs5/ST_COMG/USER/liwenhui/software/strelka/redist build
> make[1]: Entering directory `/ifs5/ST_COMG/USER/liwenhui/software/strelka/redist'
> mkdir -p vcftools-r837.tar.gz.extract.tmp; gzip -dc < vcftools-r837.tar.gz | tar -xf - -C vcftools-r837.tar.gz.extract.tmp; mv vcftools-r837.tar.gz.extract.tmp/* .; rmdir vcftools-r837.tar.gz.extract.tmp
> make -C vcftools-r837 MAKEFLAGS= && \
>         ln -sf vcftools-r837 vcftools
> make[2]: Entering directory `/ifs5/ST_COMG/USER/liwenhui/software/strelka/redist/vcftools-r837'
> make[3]: Entering directory `/ifs5/ST_COMG/USER/liwenhui/software/strelka/redist/vcftools-r837/cpp'
> g++ -c -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcftools.cpp -o vcftools.o
> g++ -MM -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcftools.cpp > vcftools.d
> g++ -c -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_file.cpp -o vcf_file.o
> g++ -MM -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_file.cpp > vcf_file.d
> g++ -c -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_entry.cpp -o vcf_entry.o
> g++ -MM -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_entry.cpp > vcf_entry.d
> g++ -c -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_entry_getters.cpp -o vcf_entry_getters.o
> g++ -MM -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_entry_getters.cpp > vcf_entry_getters.d
> g++ -c -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_entry_setters.cpp -o vcf_entry_setters.o
> g++ -MM -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_entry_setters.cpp > vcf_entry_setters.d
> g++ -c -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_file_filters.cpp -o vcf_file_filters.o
> g++ -MM -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_file_filters.cpp > vcf_file_filters.d
> g++ -c -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_file_output.cpp -o vcf_file_output.o
> vcf_file_output.cpp: In member function 'void vcf_file::output_PCA(const string&, bool, int)':
> vcf_file_output.cpp:3345:66: warning: parameter 'use_normalisation' set but not used [-Wunused-but-set-parameter]
>  void vcf_file::output_PCA(const string &output_file_prefix, bool use_normalisation, int SNP_loadings_N_PCs)
>                                                                   ^
> vcf_file_output.cpp:3345:89: warning: parameter 'SNP_loadings_N_PCs' set but not used [-Wunused-but-set-parameter]
>  void vcf_file::output_PCA(const string &output_file_prefix, bool use_normalisation, int SNP_loadings_N_PCs)
>                                                                                          ^
> vcf_file_output.cpp: In member function 'void vcf_file::output_haplotype_r2(const string&, int, int, int, int, double)':
> vcf_file_output.cpp:855:91: warning: 'D' may be used uninitialized in this function [-Wmaybe-uninitialized]
>     calc_hap_r2(e, e2, include_genotype[s], include_genotype[s2], r2, D, Dprime, chr_count);
>                                                                                            ^
> vcf_file_output.cpp: In member function 'void vcf_file::output_interchromosomal_haplotype_r2(const string&, double)':
> vcf_file_output.cpp:1079:91: warning: 'D' may be used uninitialized in this function [-Wmaybe-uninitialized]
>     calc_hap_r2(e, e2, include_genotype[s], include_genotype[s2], r2, D, Dprime, chr_count);
>                                                                                            ^
> vcf_file_output.cpp: In member function 'void vcf_file::output_haplotype_r2_of_SNP_list_vs_all_others(const string&, const string&, double)':
> vcf_file_output.cpp:1191:91: warning: 'D' may be used uninitialized in this function [-Wmaybe-uninitialized]
>     calc_hap_r2(e, e2, include_genotype[s], include_genotype[s2], r2, D, Dprime, chr_count);
>                                                                                            ^
> g++ -MM -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_file_output.cpp > vcf_file_output.d
> g++ -c -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_file_format_convert.cpp -o vcf_file_format_convert.o
> vcf_file_format_convert.cpp: In member function 'void vcf_file::output_as_012_matrix(const string&)':
> vcf_file_format_convert.cpp:414:7: warning: variable 'phase' set but not used [-Wunused-but-set-variable]
>   char phase;
>        ^
> g++ -MM -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_file_format_convert.cpp > vcf_file_format_convert.d
> g++ -c -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_file_diff.cpp -o vcf_file_diff.o
> g++ -MM -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_file_diff.cpp > vcf_file_diff.d
> g++ -c -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 parameters.cpp -o parameters.o
> g++ -MM -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 parameters.cpp > parameters.d
> g++ -c -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_file_index.cpp -o vcf_file_index.o
> g++ -MM -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 vcf_file_index.cpp > vcf_file_index.d
> g++ -c -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 output_log.cpp -o output_log.o
> g++ -MM -O2 -Wall -Wextra -D_FILE_OFFSET_BITS=64 output_log.cpp > output_log.d
> g++ vcftools.o vcf_file.o vcf_entry.o vcf_entry_getters.o vcf_entry_setters.o vcf_file_filters.o vcf_file_output.o vcf_file_format_convert.o vcf_file_diff.o parameters.o vcf_file_index.o output_log.o -o vcftools -lz
> vcf_file_format_convert.o: In function `vcf_file::output_as_012_matrix(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
> vcf_file_format_convert.cpp:(.text+0x2c9c): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
> vcf_file.o: In function `vcf_file::get_filepos()':
> vcf_file.cpp:(.text+0x422): undefined reference to `gztell64'
> vcf_file.o: In function `vcf_file::open()':
> vcf_file.cpp:(.text+0x13bd): undefined reference to `gzopen64'
> vcf_file.cpp:(.text+0x148a): undefined reference to `gzbuffer'
> vcf_file.o: In function `vcf_file::set_filepos(std::fpos<__mbstate_t>&)':
> vcf_file.cpp:(.text+0x463): undefined reference to `gzseek64'
> vcf_file_index.o: In function `vcf_file::write_index_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
> vcf_file_index.cpp:(.text+0x232): undefined reference to `gzopen64'
> vcf_file_index.o: In function `vcf_file::read_index_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
> vcf_file_index.cpp:(.text+0x76b): undefined reference to `gzopen64'
> collect2: error: ld returned 1 exit status
> make[3]: *** [vcftools] Error 1
> make[3]: Leaving directory `/ifs5/ST_COMG/USER/liwenhui/software/strelka/redist/vcftools-r837/cpp'
> /bin/sh: line 1: cd: perl: No such file or directory
> make[2]: *** [install] Error 1
> make[2]: Leaving directory `/ifs5/ST_COMG/USER/liwenhui/software/strelka/redist/vcftools-r837'
> make[1]: *** [vcftools] Error 2
> make[1]: Leaving directory `/ifs5/ST_COMG/USER/liwenhui/software/strelka/redist'
> make: *** [build] Error 2

**Comment by tmooney** [comment]
Hi!

This isn't an official repository for Strelka; everything under the "genome-vendor" organization was created to help make internal Debian packages.  We mostly use Ubuntu here, so I'm afraid we don't have much experience installing on CentOS.

I believe the current official repository for Strelka is: <https://github.com/illumina/strelka>.  They might be able to help you there!
